language: scala

scala:
  - 2.12.8
  - 2.12.9
  - 2.12.10
  - 2.13.0
  - 2.13.1

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test

jobs:
  include:
    - stage: release
      script: if [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then ./release.sh; fi
      if: tag =~ ^v
