language: scala

scala:
  - 2.11.11
  - 2.12.4
  
jdk:
  - oraclejdk8  

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/
    - redis-$REDIS_VERSION

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
